### ISSUE TITLE
docking right in Windows10 not working

### ISSUE THREAD

**Issue by utillity** [PhilipRieck/WpfAppBar#11]
in Windows10 when docking on the right side, the space is reserved, but the window is not "docked" inside that space, but to the left of it, thus consuming double the width it should be.

**Comment by SurferQuest** [comment]
From what I'm seeing, docking to any side is not working properly in Win10.  Any suggestions?

**Comment by PhilipRieck** [comment]
This should be fixed now with release 1.5.0.   (at least, is in my tests).
