### ISSUE TITLE
Window cannot be topmost when ABEdge is set to "None"

### ISSUE THREAD

**Issue by danielchalmers** [PhilipRieck/WpfAppBar#14]
Window will no longer stay on top of other windows after setting ABEdge to "None".

Tested with .NET 4.6.1 project on Windows 10 (Build 10586.104).

**Comment by PhilipRieck** [comment]
Looks like windows 10 support is iffy at best right now for some reason (unsure if it's .net version or windows 10 API changes)

**Comment by danielchalmers** [comment]
Just built the same project using .NET 4.0 and the issue still occurs.

Seems to be a Windows 10 issue.

**Comment by danielchalmers** [comment]
I have tested the following scenarios:

Windows 7,  .NET 4.0 runtime,    .NET 4.0 build
Windows 7,  .NET 4.6.1 runtime, .NET 4.0 build
Windows 7,  .NET 4.6.1 runtime, .NET 4.6.1 build
Windows 10, .NET 4.0 runtime,   .NET 4.0 build
Windows 10, .NET 4.6.1 runtime, .NET 4.0 build
Windows 10, .NET 4.6.1 runtime, .NET 4.6.1 build

And all of them have the same issue.

**Comment by PhilipRieck** [comment]
Merged your pull request and pushed to nuget.  Thanks!
