### ISSUE TITLE
Taskbar issue 

### ISSUE THREAD

**Issue by galsont** [PhilipRieck/WpfAppBar#2]
Thanks for doing this :)

When docking bottom with visible Taskbar, it shrinks the height of the application by the Taskbar height. Do this multiple times (Dock down<->up) the application will shrink to 0
Windows 8.1

**Comment by abluescarab** [comment]
Hi, was this fixed? I can't replicate this issue in Windows 8.1 Pro.

**Comment by PhilipRieck** [comment]
@abluescarab 
Some aspects of this issue were fixed with the commit for workarea fixes.   However, as I can't replicate this I haven't closed it yet.  

As an aside, the pull request you submitted for the argumentexception was merged in and the nuget package updated.

**Comment by PhilipRieck** [comment]
In my tests (VM with windows 8.1) and on windows 10, this issue no longer appears due to using the workarea rather than screen size.
