### ISSUE TITLE
Just to let you know...

### ISSUE THREAD

**Issue by tip2tail** [PhilipRieck/WpfAppBar#23]
Hi there,

Sorry to use the Issues system but was not able to find another way to message you.

I have created a similar library for WinForms.  This is based on yours and some other resources found online.

I have added a link back to your repo for WPF, perhaps you would like to do the same for WinForms?
https://github.com/tip2tail/t2tWinFormAppBarLib

Finally, thank you for your initial work - great library! :+1: 

Mark

**Comment by PhilipRieck** [comment]
Sorry I was MIA there - I've added a link back.
