### ISSUE TITLE
Question RE Pull Request

### ISSUE THREAD

**Issue by TonyValenti** [PhilipRieck/WpfAppBar#28]
Hi @PhilipRieck ,
I've been using this library for over a year now and I've run into a few issues that we've corrected and I'm wondering if our pull request would be welcome.
Issues:
1 - When you make a window toggle back and forth between being an app bar, AddHook will be called called multiple times but the hook but the hook never gets removed.
2 - When sending the resize command, it uses BeginInvoke.  This works fine when calling SetAppBar just once, but if you call it back-to-back you can get situations where things aren't executing in the order that you'd expect.  We made SetAppBar async and awaited on Dispatcher.InvokeAsync and it worked fine.

Would a pull request containing the two fixes and changes above be welcome?

**Comment by PhilipRieck** [comment]
And I'm back! 

Sorry for the long delay - a pull request would always be welcome.  For best results, I'd love if this was actually 2 pull requests, one for each issue.
