### ISSUE TITLE
Can't load the solution, VS2017

### ISSUE THREAD

**Issue by Alonzzzo2** [PhilipRieck/WpfAppBar#35]
"---------------------------
Microsoft Visual Studio
---------------------------
One or more projects in the solution were not loaded correctly.

Please see the Output Window for details.
---------------------------
OK   
---------------------------
"

**Comment by Alonzzzo2** [comment]
...\WpfAppBar-master\WpfAppBar-master\WpfAppBar\WpfAppBar.csproj : error  : Project file is incomplete. Expected imports are missing.

...\WpfAppBar-master\WpfAppBar-master\AppBarExample\AppBarExample.csproj : error  : Project file is incomplete. Expected imports are missing.

**Comment by PhilipRieck** [comment]
Visual Studio 2017 is not supported - 2019 16.9.0 or later is required.
